# Generated by Django 3.2.5 on 2021-07-17 11:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=150, verbose_name='Тип сертификата')),
            ],
            options={
                'verbose_name': 'Тип сертификата',
                'verbose_name_plural': 'Типы сертификата',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='ParseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='parse_files', verbose_name='Файл для разделения сертификатов')),
                ('calibration_certificate', models.ImageField(upload_to='', verbose_name='Сертификат для калибровки')),
                ('parsed_page', models.TextField(verbose_name='Распаршенная страница')),
                ('start_with_auto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Начало имени в сертификате (определяется автоматически)')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_files', to='certificates.certificatetype', verbose_name='Тип сертификата')),
            ],
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_types', to='certificates.course', verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='ParseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_with', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Начало имени в сертификате')),
                ('certificates', models.FileField(upload_to='certificates', verbose_name='Архив с сертификатами')),
                ('parse_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_sessions', to='certificates.parsefile', verbose_name='Файл с сертификатами')),
            ],
            options={
                'unique_together': {('parse_file_id', 'start_with')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='certificatetype',
            unique_together={('name', 'course_id')},
        ),
    ]
